apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neberi.fullname" . }}-policy
  labels:
    {{- include "neberi.labels" . | nindent 4 }}
    app.kubernetes.io/component: policy
data:
  default_rules.yaml: |
{{ .Files.Get "files/default_rules.yaml" | nindent 4 }}
