apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neberi.fullname" . }}-postgres
  labels:
    {{- include "neberi.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
  {{- /* urlquery — спецсимволы в пароле не ломают URI */}}
  DATABASE_URL: "postgresql+psycopg2://{{ .Values.postgres.user | urlquery }}:{{ .Values.postgres.password | urlquery }}@{{ include "neberi.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
