apiVersion: v1
kind: Service
metadata:
  name: {{ include "neberi.fullname" . }}-web
  labels:
    {{- include "neberi.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "neberi.name" . }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
